[package]
name = "egui_finegal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.15.0"
eframe = "0.15.0"
rand = "0.8.4"